# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7447faca8fb2c55fd6d4acdb52eb8fc0"
name = "InFlow Sync"
application_url = "https://admin-syringe-solutions.netlify.app/"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_inventory,read_products,write_products,read_publications,write_publications"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ 
  "http://localhost:8080/api/shopify/callback",
  "https://b6ba67575da4.ngrok-free.app/api/auth/callback" 
]
